DROP PROCEDURE IF EXISTS AddValidBooking;
DELIMITER //
CREATE PROCEDURE AddValidBooking(IN BookDate DATE, IN TableNo INT, IN Guests INT, IN CustId INT, IN BookingId INT)
BEGIN
DECLARE tableBooked INT DEFAULT 0;
START TRANSACTION;
SELECT COUNT(*) INTO tableBooked FROM BOOKINGS WHERE DATETIME = BookDate AND table_id  = TableNo;
IF tableBooked > 0 THEN
ROLLBACK;
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = "TABLE IS ALREADY BOOKED FOR THE GIVEN DATE";
ELSE
INSERT INTO BOOKINGS (table_id,DATETIME, NO_OF_GUESTS, Customer_CUSTOMER_ID, booking_id) VALUES (TableNo, BookDate, Guests, CustId, BookingId);
COMMIT;
END IF;
END //
DELIMITER ;
CALL AddValidBooking("2021-11-16", 2, 4,3,23);
SELECT * FROM BOOKINGS;


