DELIMITER //
CREATE PROCEDURE CancelOrder(ID INT)
BEGIN
DELETE FROM ORDERS WHERE ORDERS_ID  = ID;
SELECT CONCAT("ORDER", ID ," IS CANCELLED") AS CONFIRMATION;
END//
DELIMITER ;
CALL CancelOrder(1200);
