DROP PROCEDURE IF EXISTS CancelBooking;
DELIMITER //
CREATE PROCEDURE CancelBooking(IN BookId INT)
BEGIN
DELETE FROM BOOKINGS WHERE booking_id  = BookId;
SELECT CONCAT("BOOKING WITH ID ",BookId," IS CANCELLED") AS CONFIRMAITON;
END//
DELIMITER ;
CALL CancelBooking(24);
SELECT * FROM BOOKINGS;

