CREATE PROCEDURE CheckBooking(BookDate DATE, TableNo INT)
	SELECT CONCAT("TABLE", TableNo, "IS ALREADY BOOKED") AS BOOKING_STATUS
    WHERE EXISTS(SELECT * FROM BOOKINGS WHERE table_id = TableNo and DATETIME = BookDate);
    CALL CheckBooking("2021-11-14",4);