SELECT C.CUSTOMER_ID, C.FNAME, C.LNAME, O.ORDERS_ID, O.TOTAL_PRICE, M.MENU_ID, I.FOOD_NAME
FROM CUSTOMER AS C INNER JOIN ORDERS AS O ON C.CUSTOMER_ID = O.Customer_CUSTOMER_ID
INNER JOIN MENU AS M ON M.MENU_ID = O.Menu_MENU_ID
INNER JOIN FOOD_ITEM AS I ON M.MENU_ID = I.Menu_MENU_ID
WHERE O.TOTAL_PRICE > 150 ORDER BY O.TOTAL_PRICE ASC;
