DELIMITER //
CREATE PROCEDURE CancelOrder(IN ID INT)
BEGIN
DELETE FROM ORDER_DELIVERY_STATUS WHERE ORDERS_ORDERS_ID = ID;
DELETE FROM ORDERS WHERE ORDERS_ID = ID;
END//
DELIMITER ;

CALL CancelOrder(1005);
