DROP PROCEDURE IF EXISTS UpdateBooking;
DELIMITER //
CREATE PROCEDURE UpdateBooking(IN BookId INT, IN BookDate DATE)
BEGIN
UPDATE BOOKINGS SET DATETIME = BookDate WHERE booking_id  = BookId;
SELECT CONCAT("BOOKING ID ", BookId, "IS UPDATED") AS CONFIRMATION;
END//
DELIMITER ;
CALL UpdateBooking(24,"2021-11-19");
SELECT * FROM BOOKINGS;